services:
  discord-bot:
    build: ./discord-bot
    env_file: .env
    depends_on:
      - language-model
      - audio-processor
    networks:
      - app-network

  language-model:
    build: ./services/language-model
    env_file: .env
    networks:
      - app-network

  audio-processor:
    build: ./services/audio-processor
    env_file: .env
    depends_on:
      - language-model
    volumes:
      - ./google-cloud-credentials.json:/app/google-cloud-credentials.json:ro
    networks:
      - app-network

  database-manager:
    build: ./services/database-manager
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: