apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      serviceAccountName: k8s-secret-reader
      containers:
      - name: discord-bot
        image: us-central1-docker.pkg.dev/discord-bots-442605/discord-bot-repo/discord-bot:latest
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT_ID
          value: discord-bots-442605
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-service
spec:
  selector:
    app: discord-bot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000