apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: language-model
  template:
    metadata:
      labels:
        app: language-model
    spec:
      serviceAccountName: k8s-secret-reader
      containers:
      - name: language-model
        image: us-central1-docker.pkg.dev/discord-bots-442605/discord-bot-repo/language-model:latest
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT_ID
          value: discord-bots-442605
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: language-model-service
spec:
  selector:
    app: language-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002