apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: language-model
  template:
    metadata:
      labels:
        app: language-model
    spec:
      containers:
      - name: language-model
        image: gcr.io/lookslikeivelost/language-model:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: language-model-service
spec:
  selector:
    app: language-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
