name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Lowercase Owner
      run: |
        echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

    - name: Build and Push Discord Bot Image
      uses: docker/build-push-action@v5
      with:
        context: ./discord-bot
        file: ./bot/Dockerfile
        push: true
        tags: ghcr.io/${{ env.OWNER }}/discord-bot:latest

    - name: Build and Push Audio Processor Image
      uses: docker/build-push-action@v5
      with:
        context: ./services/audio-processor
        file: ./services/audio-processor/Dockerfile
        push: true
        tags: ghcr.io/${{ env.OWNER }}/audio-processor:latest

    - name: Build and Push Language Model Image
      uses: docker/build-push-action@v5
      with:
        context: ./services/language-model
        file: ./services/language-model/Dockerfile
        push: true
        tags: ghcr.io/${{ env.OWNER }}/language-model:latest
